[project]
name = 'Git-Workflow-Chaos-Engine'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.branch-naming-convention-anarchist]
path = 'contracts/branch-naming-convention-anarchist.clar'
clarity_version = 3
epoch = 'latest'

[contracts.commit-message-cryptographer]
path = 'contracts/commit-message-cryptographer.clar'
clarity_version = 3
epoch = '3.2'

[contracts.merge-conflict-resurrection-necromancer]
path = 'contracts/merge-conflict-resurrection-necromancer.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
